name: Ensure Issue Has a Label and Auto-Assign Label (Python)

on:
  issues:
    types: [opened, edited]  # Trigger when an issue is opened or edited

jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (latest version)
        uses: actions/setup-python@v2
        with:
          python-version: 'latest'  # Automatically uses the latest stable version of Python

      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script to handle labels
        run: |
          python scripts/label_issues.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}